/**
 * Build-time string table for static site generation. Not loaded in the browser.
 */
const STR = {
    en: {
      brand: "PlainBytes Redactor",
      nav_home: "Home",
      nav_guide: "User Guide",
      nav_features: "Features",
      nav_regional: "Regional Rules",
      nav_roadmap: "Roadmap",
      nav_support: "Support",
      nav_download: "Get on Microsoft Store",
      hero_kicker: "plainbytes redactor",
      hero_h1: "PlainBytes Redactor",
      hero_tagline: "Redact PDFs without sending client data anywhere.",
      hero_lead:
        "Runs entirely on your computer — no cloud upload, no AI service seeing your files. Automatic detection for 28 countries' identifier formats, plus manual review before you export.",
      hero_cta_primary: "Get on Microsoft Store",
      hero_cta_secondary: "Watch Demo",
      hero_badge_1: "100% offline",
      hero_badge_2: "Physical redaction",
      hero_badge_3: "28 countries",
      hero_badge_4: "Manual review",
      hero_note: "10-day free trial · One-time purchase · No subscription",
      hero_mockup_alt: "PlainBytes Redactor main window with PDF open and detection panel",
      hero_video: "Product demo video (12–15 s loop) — replace with your hosted MP4 or embed.",
      trust_title: "Why processing stays local",
      trust_body_p1:
        "Most redaction tools — especially the AI-powered ones — upload your documents to a server before they can find and remove sensitive information. For anyone bound by confidentiality, privilege, or audit independence rules, that's a risk you shouldn't have to take just to redact a file.",
      trust_body_p2:
        "PlainBytes Redactor does all detection and processing on your own device. Your files never leave your computer, and there's no account, no sync, and no server in the loop.",
      section_how_title: "How it works",
      wf_kicker: "how it works",
      wf_title: "From open file to redacted export",
      wf_step1_title: "Open & scan",
      wf_step1_desc: "Load a PDF and run detection for your region's formats.",
      wf_step2_title: "Review flags",
      wf_step2_desc: "See every flagged item with its risk category.",
      wf_step3_title: "Adjust by hand",
      wf_step3_desc: "Add, remove, or fine-tune before finalizing.",
      wf_step4_title: "Export",
      wf_step4_desc: "Content and metadata permanently removed.",
      how_li1:
        "Automatic detection — Identifies names, ID numbers, phone numbers, addresses, and financial account numbers across 28 countries' formats, so you're not starting from a blank page.",
      how_li2:
        "Manual review panel — Check every flagged item before export. Add, remove, or adjust redactions by hand — the automation is a starting point, not the final say.",
      how_li3:
        "True removal, not masking — Redacted content is stripped from the underlying file, not just covered with a black box. Metadata that could expose sensitive information is removed too.",
      how_li4: "Batch processing — Apply the same rules across multiple files at once.",
      scenarios_title: "Built for how solo practitioners actually work",
      scenario_attorney_label: "For attorneys",
      scenario_attorney_body:
        "Redact Social Security numbers, financial details, and other PII before e-filing or sharing discovery documents — without routing client files through a third-party cloud service.",
      scenario_accountant_label: "For accountants",
      scenario_accountant_body:
        "Redact account numbers, Social Security numbers, and client financial details before sharing audit working papers, tax filings, or year-end reports — without routing client data through a third-party cloud service.",
      scenario_hr_label: "For HR teams",
      scenario_hr_body:
        "Redact salary figures, Social Security numbers, and personal details before sharing offer letters, termination records, or personnel files with auditors, legal counsel, or in response to data requests.",
      scenario_attorney:
        "For attorneys — Redact Social Security numbers, financial details, and other PII before e-filing or sharing discovery documents, without routing client files through a third-party cloud service.",
      scenario_accountant:
        "For accountants — Redact account numbers, Social Security numbers, and client financial details before sharing audit working papers, tax filings, or year-end reports, without routing client data through a third-party cloud service.",
      scenario_hr:
        "For HR teams — Redact salary figures, Social Security numbers, and personal details before sharing offer letters, termination records, or personnel files with auditors, legal counsel, or in response to data requests.",
      pricing_title: "Pricing",
      pricing_amount: "$34",
      pricing_amount_suffix: " one-time",
      pricing_card_body:
        "10-day full-feature trial, then a single payment. No subscription, no recurring fees.",
      pricing_cta: "Start free trial",
      pricing_body:
        "Try every feature free for 10 days. After that, a one-time payment of $34 unlocks the full version — no subscription, no recurring fees.",
      included_title: "What's included today",
      included_li1: "Physical redaction",
      included_li2: "12-language interface",
      included_li3: "28 countries' rule coverage",
      included_li4: "Batch processing",
      included_roadmap: "Full roadmap on GitHub",
      trust_tag1: "No cloud upload",
      trust_tag2: "Offline AI inference",
      trust_tag3: "Physical redaction export",
      pillar1_h: "100% Offline Processing",
      pillar1_p:
        "No account required. No document upload. AI inference, rule matching, and PDF rendering run locally on your machine and continue to work in offline environments.",
      pillar2_h: "Physical Redaction Export",
      pillar2_p:
        "Go beyond visual masking. PlainBytes Redactor exports physically redacted PDFs and removes common metadata traces to reduce recovery risk during sharing and archiving.",
      pillar3_h: "On-Device AI + Regional Rules",
      pillar3_p:
        "Use local multilingual AI to identify names, organizations, and locations, and combine it with built-in regional rules for IDs, phone numbers, bank cards, tax identifiers, and other structured data.",
      section_everything: "Everything you need",
      section_everything_lead: "Detect, review, redact, and export — all offline.",
      everything_li1: "Side-by-side audit trace with grouped items and clear risk cues",
      everything_li2: "Physical redaction export — sensitive content removed from PDF streams, not just covered",
      everything_li3: "On-device AI plus 145+ built-in regional rules for structured data",
      everything_li4: "Batch workflows: apply confirmed marks from a baseline PDF to similar files",
      everything_li5: "100% private — no cloud, no uploads, strictly offline",
      everything_li6: "12-language UI · fast native rendering · metadata-aware export",
      regional_title: "Regional detection rules built in",
      regional_intro: "Browse built-in detection coverage across major regions and document types.",
      regional_li1: "20+ covered regions",
      regional_li2: "145+ built-in rules",
      regional_li3: "Common categories: ID documents, tax numbers, bank cards / account identifiers, phone numbers, postal codes, business identifiers",
      regional_line: "Not just pattern matching. A practical regional rule library designed for real document review.",
      workflow_title: "Review Faster. Export Safer.",
      wf1_h: "Side-by-Side Review",
      wf1_p: "See detected items and document content together, then confirm or adjust results before export.",
      wf2_h: "Batch Processing for Similar PDFs",
      wf2_p: "Apply the current document's reviewed redaction results to similar PDF files and process them in batches.",
      wf3_h: "Focused Audit Trace Panel",
      wf3_p: "Review grouped sensitive items with clear risk cues, reduce duplicate confirmation work, and keep the workflow easy to follow.",
      early_title: "Why Free During Early Access",
      early_body:
        "PlainBytes Redactor is currently free during its early adopter phase. Our focus is to validate real-world workflows, improve detection quality across document formats and regions, and refine product stability with feedback from professional users.",
      early_c1: "Core local-first architecture will remain a foundational product principle.",
      early_c2: "We do not rely on cloud upload for core redaction workflows.",
      early_c3: "Early users help shape the product roadmap and quality baseline.",
      early_note:
        "We do not promise permanent free access for all future core features, absolute security guarantees, or formal compliance certifications the product does not hold.",
      rm_v10: "v1.0 (Current)",
      rm_v10_li1: "Core physical redaction workflow",
      rm_v10_li2: "12-language interface",
      rm_v10_li3: "20+ regional rule coverage",
      rm_v10_li4: "Batch processing",
      rm_v12: "v1.2 (Planned)",
      rm_v12_li1: "Offline OCR for scanned PDFs",
      rm_v12_li2: "Custom rule editor",
      rm_v15: "v1.5 (Planned)",
      rm_v15_li1: "Local audit report export",
      rm_v15_li2: "More verification and review tooling",
      rm_v20: "v2.0 (Vision)",
      rm_v20_li1: "Cross-platform support",
      rm_v20_li2: "Advanced semantic masking workflows",
      foot_dl: "Download & security",
      foot_store: "Microsoft Store",
      foot_vt: "VirusTotal scan (when available)",
      foot_sup: "Support & feedback",
      foot_gh: "GitHub",
      foot_email: "Support email",
      foot_doc: "Documentation",
      foot_quick: "Quick Start Guide",
      foot_privacy: "Privacy Policy",
      copy: "© 2026 PlainBytes Studio",
      quickstart_title: "Quick Start",
      quickstart_body:
        "Install from the Microsoft Store or your distributed package. Open a PDF, run detection, review items in the audit panel, confirm redactions, then export. For batch workflows, apply confirmed marks from a baseline document to additional files. See the in-app help and rule center for regional coverage.",
      privacy_title: "Privacy Policy",
      privacy_body:
        "PlainBytes Redactor is designed to process PDFs on your device without sending document content to PlainBytes servers for core redaction workflows. Update this page with your legal entity details, data categories, and contact information before publication. This placeholder is not legal advice.",
    },
    zh: {
      brand: "PlainBytes Redactor",
      nav_home: "首页",
      nav_guide: "使用手册",
      nav_features: "功能",
      nav_regional: "区域规则",
      nav_roadmap: "路线图",
      nav_support: "支持",
      nav_download: "在 Microsoft Store 获取",
      hero_kicker: "PlainBytes Redactor",
      hero_h1: "PlainBytes Redactor",
      hero_tagline: "脱敏 PDF，客户数据无需离开本机。",
      hero_lead:
        "PlainBytes Redactor 完全在您的电脑上运行——不上传云端，没有 AI 服务查看您的文件。支持 28 国/地区标识符格式的自动检测，导出前可人工复核。",
      hero_cta_primary: "在 Microsoft Store 获取",
      hero_cta_secondary: "观看演示",
      hero_badge_1: "100% 离线",
      hero_badge_2: "物理脱敏",
      hero_badge_3: "28 国/地区",
      hero_badge_4: "人工复核",
      hero_note: "10 天全功能免费试用 · 一次性购买 · 无订阅",
      hero_video: "产品演示视频（约 12–15 秒循环）— 请替换为托管的 MP4 或嵌入播放器。",
      trust_title: "为什么处理必须留在本地",
      trust_body_p1:
        "大多数脱敏工具——尤其是 AI 驱动的——需要先把文档上传到服务器才能查找并删除敏感信息。对受保密义务、特权规则或审计独立性约束的人而言，仅为脱敏一份文件就承担这种风险并不合理。",
      trust_body_p2:
        "PlainBytes Redactor 在您自己的设备上完成全部检测与处理。文件不会离开您的电脑，无需账号、无需同步、也没有服务器参与。",
      section_how_title: "工作原理",
      wf_kicker: "工作原理",
      wf_title: "从打开文件到脱敏导出",
      wf_step1_title: "打开并扫描",
      wf_step1_desc: "加载 PDF，按您所在地区的格式运行检测。",
      wf_step2_title: "复核标记",
      wf_step2_desc: "查看每项标记及其风险类别。",
      wf_step3_title: "手动调整",
      wf_step3_desc: "定稿前可添加、删除或微调。",
      wf_step4_title: "导出",
      wf_step4_desc: "内容与元数据永久移除。",
      how_li1:
        "自动检测 — 识别 28 国/地区格式下的姓名、证件号、电话、地址与金融账号，无需从零开始。",
      how_li2:
        "人工复核面板 — 导出前逐项检查标记结果，可手动添加、删除或调整脱敏区域；自动化是起点，不是最终结论。",
      how_li3:
        "真正删除，而非遮盖 — 从 PDF 底层移除敏感内容，而非仅加黑框；同时清理可能泄露信息的元数据。",
      how_li4: "批量处理 — 将同一套规则一次性应用到多个文件。",
      scenarios_title: "为个体执业者的实际工作方式而设计",
      scenario_attorney_label: "律师",
      scenario_attorney_body:
        "在电子提交或共享证据材料前，脱敏社保号、财务信息及其他 PII，无需将客户文件经第三方云服务中转。",
      scenario_accountant_label: "会计师",
      scenario_accountant_body:
        "在共享审计工作底稿、纳税申报或年终报告前，脱敏账号、社保号及客户财务细节，无需将客户数据经第三方云服务中转。",
      scenario_hr_label: "人力资源团队",
      scenario_hr_body:
        "在与审计师、法律顾问共享或响应数据请求前，脱敏录用函、离职记录或人事档案中的薪资、社保号及个人细节。",
      scenario_attorney:
        "律师 — 在电子提交或共享证据材料前，脱敏社保号、财务信息及其他 PII，无需将客户文件经第三方云服务中转。",
      scenario_accountant:
        "会计师 — 在共享审计工作底稿、纳税申报或年终报告前，脱敏账号、社保号及客户财务细节，无需将客户数据经第三方云服务中转。",
      included_title: "当前包含的功能",
      included_li1: "物理脱敏",
      included_li2: "12 种界面语言",
      included_li3: "28 国/地区规则覆盖",
      included_li4: "批量处理",
      pricing_title: "定价",
      pricing_body: "10 天免费试用全部功能。之后一次性支付 $34 解锁完整版——无订阅、无周期性费用。",
      trust_tag1: "无云端上传",
      trust_tag2: "离线 AI 推理",
      trust_tag3: "物理脱敏导出",
      pillar1_h: "100% 离线处理",
      pillar1_p:
        "无需账号、不上传文档。AI 推理、规则匹配与 PDF 渲染在本地运行，在离线环境下仍可使用。",
      pillar2_h: "物理脱敏导出",
      pillar2_p:
        "不止视觉遮盖。PlainBytes Redactor 导出经物理脱敏的 PDF，并清理常见元数据痕迹，以降低分享与归档场景下的恢复风险。",
      pillar3_h: "端侧 AI + 区域规则",
      pillar3_p:
        "使用本地多语言 AI 识别姓名、机构与地点，并结合内置区域规则覆盖证件、电话、银行卡、税务标识等结构化数据。",
      section_everything: "一站式能力",
      section_everything_lead: "检测、复核、脱敏与导出 — 全程离线。",
      everything_li1: "并排审计追踪：分组敏感项与风险提示",
      everything_li2: "物理脱敏导出：从内容流移除敏感信息，而非仅视觉遮盖",
      everything_li3: "端侧 AI 与 145+ 条内置区域规则，覆盖结构化数据",
      everything_li4: "批量：将基准文档中已确认的标注应用到相似 PDF",
      everything_li5: "100% 私密：无云端、无上传，严格离线",
      everything_li6: "12 种界面语言 · 原生高速渲染 · 导出时关注元数据",
      regional_title: "内置区域检测规则",
      regional_intro: "了解主要地区与文档类型下的内置检测覆盖。",
      regional_li1: "覆盖 20+ 地区",
      regional_li2: "145+ 条内置规则",
      regional_li3: "常见类别：证件、税号、银行卡/账户标识、电话、邮编、商业标识等",
      regional_line: "不仅是模式匹配，更是面向真实审阅场景的区域规则库。",
      workflow_title: "复核更快，导出更稳",
      wf1_h: "并排审阅",
      wf1_p: "同时查看检测项与文档内容，在导出前确认或调整结果。",
      wf2_h: "相似 PDF 批量处理",
      wf2_p: "将当前文档已复核的脱敏结果应用到相似 PDF，批量处理。",
      wf3_h: "聚焦的审计追踪面板",
      wf3_p: "分组查看敏感项与风险提示，减少重复确认，流程更清晰。",
      early_title: "早期访问为何免费",
      early_body:
        "PlainBytes Redactor 在早期采用者阶段免费提供。我们专注于验证真实工作流、提升多格式与多地区检测质量，并在专业用户反馈下提升稳定性。",
      early_c1: "本地优先的核心架构将继续作为产品基石。",
      early_c2: "核心脱敏工作流不依赖云端上传。",
      early_c3: "早期用户共同塑造路线图与质量基线。",
      early_note:
        "我们不承诺所有未来核心功能永久免费、绝对安全，或提供产品未正式取得的合规认证。",
      rm_v10: "v1.0（当前）",
      rm_v10_li1: "核心物理脱敏流程",
      rm_v10_li2: "12 种界面语言",
      rm_v10_li3: "20+ 地区规则覆盖",
      rm_v10_li4: "批量处理",
      rm_v12: "v1.2（计划中）",
      rm_v12_li1: "扫描件 PDF 离线 OCR",
      rm_v12_li2: "自定义规则编辑器",
      rm_v15: "v1.5（计划中）",
      rm_v15_li1: "本地审计报告导出",
      rm_v15_li2: "更多校验与审阅工具",
      rm_v20: "v2.0（愿景）",
      rm_v20_li1: "跨平台支持",
      rm_v20_li2: "进阶语义脱敏工作流",
      foot_dl: "下载与安全",
      foot_store: "Microsoft Store",
      foot_vt: "VirusTotal 扫描（如有）",
      foot_sup: "支持与反馈",
      foot_gh: "GitHub",
      foot_email: "支持邮箱",
      foot_doc: "文档",
      foot_quick: "快速入门",
      foot_privacy: "隐私政策",
      copy: "© 2026 PlainBytes Studio. 保留所有权利。",
      quickstart_title: "快速入门",
      quickstart_body:
        "从 Microsoft Store 或您分发的安装包安装。打开 PDF、运行检测、在审计面板中复核、确认脱敏项后导出。批量场景下可将基准文档中已确认的标注应用到更多文件。详见应用内帮助与规则中心。",
      privacy_title: "隐私政策",
      privacy_body:
        "PlainBytes Redactor 的核心脱敏流程在您的设备上处理 PDF，不向 PlainBytes 服务器上传文档内容。正式发布前请补充法律主体、数据类别与联系方式。本页为占位说明，不构成法律意见。",
    },
    ja: {
      brand: "PlainBytes Redactor",
      nav_home: "ホーム",
      nav_guide: "ユーザーガイド",
      nav_features: "機能",
      nav_regional: "地域ルール",
      nav_roadmap: "ロードマップ",
      nav_support: "サポート",
      nav_download: "Microsoft Store で入手",
      hero_kicker: "PlainBytes Redactor",
      hero_tagline: "クライアントデータを外部に送らず PDF を編集。",
      hero_lead:
        "PlainBytes Redactor はすべてお使いの PC 上で動作します。クラウドへのアップロードも、ファイルを見る AI サービスもありません。28 か国・地域の識別子形式を自動検出し、エクスポート前に手動レビューできます。",
      hero_cta_secondary: "デモを見る",
      hero_badge_3: "28 か国・地域",
      hero_badge_4: "手動レビュー",
      hero_note: "10 日間全機能無料トライアル · 買い切り · サブスクなし",
      trust_title: "処理がローカルに留まる理由",
      trust_body_p1:
        "多くの編集ツール、特に AI 駆動のものは、機密情報を見つけて削除する前に文書をサーバーにアップロードします。守秘義務、特権、監査独立性のルールに縛られる方にとって、ファイル編集のためにそのリスクを負う必要はありません。",
      trust_body_p2:
        "PlainBytes Redactor は検出と処理をすべてお使いのデバイス上で行います。ファイルは PC から出ず、アカウント、同期、サーバーも不要です。",
      section_how_title: "仕組み",
      wf_kicker: "仕組み",
      wf_title: "ファイルを開いてから編集してエクスポートまで",
      wf_step1_title: "開いてスキャン",
      wf_step1_desc: "PDF を読み込み、お住まいの地域の形式で検出を実行します。",
      wf_step2_title: "フラグを確認",
      wf_step2_desc: "リスクカテゴリ付きですべてのフラグ項目を表示します。",
      wf_step3_title: "手動で調整",
      wf_step3_desc: "確定前に追加・削除・微調整ができます。",
      wf_step4_title: "エクスポート",
      wf_step4_desc: "コンテンツとメタデータを恒久的に削除します。",
      how_li1:
        "自動検出 — 28 か国・地域の形式で氏名、ID、電話、住所、金融口座番号などを識別。白紙から始める必要はありません。",
      how_li2:
        "手動レビューパネル — エクスポート前にフラグ付き項目をすべて確認。追加・削除・調整も可能。自動化は出発点であり、最終判断ではありません。",
      how_li3:
        "マスキングではなく真正な削除 — 黒塗りではなく PDF 本体から内容を除去。機密を示す可能性のあるメタデータも削除します。",
      how_li4: "バッチ処理 — 同じルールを複数ファイルに一度に適用。",
      scenarios_title: "個人開業者の実務に合わせて設計",
      scenario_attorney_label: "弁護士向け",
      scenario_attorney_body:
        "電子提出やディスカバリー共有前に SSN、財務情報、その他 PII を編集。クライアントファイルを第三者クラウド経由にしません。",
      scenario_accountant_label: "会計士向け",
      scenario_accountant_body:
        "監査調書、税務申告、期末報告書を共有する前に、口座番号、SSN、顧客の財務情報を編集。顧客データを第三者クラウド経由にしません。",
      scenario_hr_label: "人事向け",
      scenario_hr_body:
        "監査人、法務担当者への共有やデータ開示請求への対応前に、オファーレター、退職記録、人事ファイルから給与、SSN、個人情報を編集します。",
      scenario_attorney:
        "弁護士向け — 電子提出やディスカバリー共有前に SSN、財務情報、その他 PII を編集。クライアントファイルを第三者クラウド経由にしません。",
      scenario_accountant:
        "会計士向け — 監査調書、税務申告、期末報告書を共有する前に、口座番号、SSN、顧客の財務情報を編集。顧客データを第三者クラウド経由にしません。",
      included_title: "現在含まれる機能",
      included_li1: "物理レダクション",
      included_li2: "12 言語 UI",
      included_li3: "28 か国・地域のルール",
      included_li4: "バッチ処理",
      pricing_title: "価格",
      pricing_body:
        "10 日間、すべての機能を無料でお試しください。その後、$34 の買い切りでフル版が利用可能 — サブスクや継続課金はありません。",
      trust_tag1: "クラウド非アップロード",
      trust_tag2: "オフライン AI 推論",
      trust_tag3: "物理レダクション出力",
      pillar1_h: "100% オフライン処理",
      pillar1_p:
        "アカウント不要、アップロード不要。AI・ルール照合・レンダリングはローカルで動作し、オフライン環境でも利用できます。",
      pillar2_h: "物理レダクションのエクスポート",
      pillar2_p:
        "視覚的な隠しだけではありません。物理的にレダクションした PDF を出力し、一般的なメタデータを削減し、共有・アーカイブ時の復元リスクを低減します。",
      pillar3_h: "オンデバイス AI と地域ルール",
      pillar3_p:
        "多言語 AI で氏名・組織・地名を検出し、身分証、電話、カード、税務 ID など構造化データ用の地域ルールと組み合わせます。",
      section_everything: "必要なものが揃う",
      section_everything_lead: "検出、レビュー、レダクション、エクスポート — すべてオフライン。",
      everything_li1: "並列監査トレース：グループ化とリスク表示で確認しやすく",
      everything_li2: "物理レダクション出力：視覚的な隠しではなくストリームから除去",
      everything_li3: "オンデバイス AI と 145+ の組み込み地域ルールで構造化データをカバー",
      everything_li4: "バッチ：基準 PDF の確認済みマークを類似ファイルへ適用",
      everything_li5: "100% プライベート：クラウドなし、アップロードなし、厳密にオフライン",
      everything_li6: "12 言語 UI · 高速ネイティブ描画 · メタデータを意識したエクスポート",
      regional_title: "組み込みの地域検出ルール",
      regional_intro: "主要地域・文書タイプのカバレッジをご覧ください。",
      regional_li1: "20 以上の地域",
      regional_li2: "145 以上の組み込みルール",
      regional_li3: "主なカテゴリ：身分証、税番号、銀行カード／口座、電話、郵便番号、事業者識別子 など",
      regional_line: "単なるパターン一致ではなく、実務レビュー向けの地域ルールライブラリ。",
      workflow_title: "素早く確認、安全に出力",
      wf1_h: "並べてレビュー",
      wf1_p: "検出項目と文書を同時に確認し、エクスポート前に調整できます。",
      wf2_h: "類似 PDF の一括処理",
      wf2_p: "現在の文書で確認済みの結果を類似 PDF に適用し、バッチ処理します。",
      wf3_h: "監査トレースに集中",
      wf3_p: "グループ化された項目とリスク表示で重複確認を減らし、流れを分かりやすくします。",
      early_title: "アーリーアクセスが無料の理由",
      early_body:
        "PlainBytes Redactor はアーリーアダプター期間中は無料です。実務フローの検証、フォーマット・地域横断の検出品質向上、安定性の向上に注力しています。",
      early_c1: "ローカル優先の核は製品の基本原則として維持します。",
      early_c2: "コア編集フローはクラウドアップロードに依存しません。",
      early_c3: "早期ユーザーがロードマップと品質基線を形作ります。",
      early_note:
        "将来の全コア機能の永久無料、絶対的な安全性、または未取得のコンプライアンス認証は約束しません。",
      rm_v10: "v1.0（現行）",
      rm_v10_li1: "物理レダクションの中核フロー",
      rm_v10_li2: "12 言語 UI",
      rm_v10_li3: "20+ 地域ルール",
      rm_v10_li4: "バッチ処理",
      rm_v12: "v1.2（予定）",
      rm_v12_li1: "スキャン PDF のオフライン OCR",
      rm_v12_li2: "カスタムルールエディター",
      rm_v15: "v1.5（予定）",
      rm_v15_li1: "ローカル監査レポート出力",
      rm_v15_li2: "検証・レビュー機能の拡充",
      rm_v20: "v2.0（ビジョン）",
      rm_v20_li1: "クロスプラットフォーム",
      rm_v20_li2: "高度なセマンティックマスキング",
      foot_dl: "ダウンロードとセキュリティ",
      foot_store: "Microsoft Store",
      foot_vt: "VirusTotal スキャン（準備でき次第）",
      foot_sup: "サポートとフィードバック",
      foot_gh: "GitHub",
      foot_email: "サポートメール",
      foot_doc: "ドキュメント",
      foot_quick: "クイックスタート",
      foot_privacy: "プライバシーポリシー",
      copy: "© 2026 PlainBytes Studio. All rights reserved.",
      quickstart_title: "クイックスタート",
      quickstart_body:
        "Microsoft Store または配布パッケージからインストールします。PDF を開き、検出を実行し、監査パネルで確認してからエクスポートします。バッチでは基準ドキュメントの確認済みマークを他ファイルに適用できます。アプリ内ヘルプとルールセンターを参照してください。",
      privacy_title: "プライバシーポリシー",
      privacy_body:
        "コアの編集フローは端末上で PDF を処理し、PlainBytes サーバーに文書内容を送信しません。公開前に事業者情報・データの種類・連絡先を記載してください。本ページはプレースホルダーであり法的助言ではありません。",
    },
    de: {
      brand: "PlainBytes Redactor",
      nav_home: "Startseite",
      nav_guide: "Benutzerhandbuch",
      nav_features: "Funktionen",
      nav_regional: "Regionale Regeln",
      nav_roadmap: "Roadmap",
      nav_support: "Support",
      nav_download: "Im Microsoft Store",
      hero_kicker: "PlainBytes Redactor",
      hero_tagline: "PDFs redigieren, ohne Mandantendaten irgendwohin zu senden.",
      hero_lead:
        "PlainBytes Redactor läuft vollständig auf Ihrem Computer — kein Cloud-Upload, kein KI-Dienst sieht Ihre Dateien. Automatische Erkennung für Kennungen aus 28 Ländern, plus manuelle Prüfung vor dem Export.",
      hero_cta_secondary: "Demo ansehen",
      hero_badge_3: "28 Länder",
      hero_badge_4: "Manuelle Prüfung",
      hero_note: "10 Tage kostenlos testen · Einmaliger Kauf · Kein Abo",
      trust_title: "Warum die Verarbeitung lokal bleibt",
      trust_body_p1:
        "Die meisten Redaktionstools — besonders KI-gestützte — laden Dokumente auf einen Server hoch, bevor sie sensible Informationen finden und entfernen können. Wer Vertraulichkeit, Privilegien oder Prüfungsunabhängigkeit wahren muss, sollte dieses Risiko nicht nur für eine Datei eingehen müssen.",
      trust_body_p2:
        "PlainBytes Redactor führt Erkennung und Verarbeitung auf Ihrem Gerät durch. Ihre Dateien verlassen Ihren Computer nicht — kein Konto, keine Synchronisation, kein Server.",
      section_how_title: "So funktioniert es",
      wf_kicker: "So funktioniert es",
      wf_title: "Vom Öffnen bis zum redigierten Export",
      wf_step1_title: "Öffnen & scannen",
      wf_step1_desc: "PDF laden und Erkennung für die Formate Ihrer Region ausführen.",
      wf_step2_title: "Markierungen prüfen",
      wf_step2_desc: "Jeden markierten Eintrag mit Risikokategorie anzeigen.",
      wf_step3_title: "Manuell anpassen",
      wf_step3_desc: "Vor dem Abschluss hinzufügen, entfernen oder feinjustieren.",
      wf_step4_title: "Export",
      wf_step4_desc: "Inhalt und Metadaten dauerhaft entfernt.",
      how_li1:
        "Automatische Erkennung — Namen, Ausweisnummern, Telefon, Adressen und Kontonummern in 28 Länderformaten — kein Start bei null.",
      how_li2:
        "Manuelles Prüfpanel — Jedes markierte Element vor dem Export prüfen. Ergänzen, entfernen oder anpassen — Automatisierung ist der Start, nicht das letzte Wort.",
      how_li3:
        "Echte Entfernung, kein Maskieren — Inhalte werden aus der Datei entfernt, nicht nur überdeckt. Metadaten mit sensiblen Hinweisen werden ebenfalls bereinigt.",
      how_li4: "Stapelverarbeitung — dieselben Regeln auf mehrere Dateien anwenden.",
      scenarios_title: "Für die Arbeitsweise einzelner Praktiker",
      scenario_attorney_label: "Für Anwälte",
      scenario_attorney_body:
        "SSN, Finanzdaten und andere PII vor E-Filing oder Discovery-Austausch redigieren, ohne Mandantenakten über Cloud-Dienste zu leiten.",
      scenario_accountant_label: "Für Steuerberater",
      scenario_accountant_body:
        "Kontonummern, SSN und Mandanten-Finanzdaten redigieren, bevor Prüfungsunterlagen, Steuererklärungen oder Jahresabschlussberichte geteilt werden — ohne Mandantendaten über Cloud-Dienste Dritter zu leiten.",
      scenario_hr_label: "Für HR-Teams",
      scenario_hr_body:
        "Gehälter, SSN und persönliche Angaben redigieren, bevor Angebotsschreiben, Kündigungsunterlagen oder Personalakten mit Wirtschaftsprüfern, Rechtsberatern geteilt oder für Datenauskünfte verwendet werden.",
      scenario_attorney:
        "Für Anwälte — SSN, Finanzdaten und andere PII vor E-Filing oder Discovery-Austausch redigieren, ohne Mandantenakten über Cloud-Dienste zu leiten.",
      scenario_accountant:
        "Für Steuerberater — Kontonummern, SSN und Mandanten-Finanzdaten redigieren, bevor Prüfungsunterlagen, Steuererklärungen oder Jahresabschlussberichte geteilt werden, ohne Mandantendaten über Cloud-Dienste Dritter zu leiten.",
      included_title: "Heute enthalten",
      included_li1: "Physische Redaktion",
      included_li2: "12 UI-Sprachen",
      included_li3: "Regeln für 28 Länder",
      included_li4: "Stapelverarbeitung",
      pricing_title: "Preise",
      pricing_body:
        "10 Tage alle Funktionen kostenlos testen. Danach einmalig $34 für die Vollversion — kein Abo, keine laufenden Gebühren.",
      trust_tag1: "Kein Cloud-Upload",
      trust_tag2: "Offline-KI-Inferenz",
      trust_tag3: "Physische Redaktion beim Export",
      pillar1_h: "100 % Offline-Verarbeitung",
      pillar1_p:
        "Kein Konto, kein Upload. KI, Regelabgleich und Rendering laufen lokal und funktionieren offline.",
      pillar2_h: "Physische Redaktion beim Export",
      pillar2_p:
        "Mehr als visuelle Abdeckung: physisch redigierte PDFs und gängige Metadaten werden reduziert, um Wiederherstellungsrisiken zu verringern.",
      pillar3_h: "KI auf dem Gerät + regionale Regeln",
      pillar3_p:
        "Mehrsprachige lokale KI für Namen, Organisationen und Orte, kombiniert mit regionalen Regeln für Ausweise, Telefon, Karten, Steuer-IDs und mehr.",
      section_everything: "Alles, was Sie brauchen",
      section_everything_lead: "Erkennen, prüfen, schwärzen und exportieren — vollständig offline.",
      everything_li1: "Audit-Trace nebeneinander: gruppierte Treffer und klare Risiko-Hinweise",
      everything_li2: "Physische Redaktion: sensible Inhalte aus Streams entfernt, nicht nur überdeckt",
      everything_li3: "KI auf dem Gerät plus 145+ eingebaute regionale Regeln für strukturierte Daten",
      everything_li4: "Stapel: bestätigte Markierungen vom Basis-PDF auf ähnliche Dateien anwenden",
      everything_li5: "100 % privat — keine Cloud, keine Uploads, strikt offline",
      everything_li6: "12 UI-Sprachen · schnelles natives Rendering · metadatenbewusster Export",
      regional_title: "Eingebaute regionale Erkennungsregeln",
      regional_intro: "Überblick über die Abdeckung nach Region und Dokumenttyp.",
      regional_li1: "20+ Regionen",
      regional_li2: "145+ eingebaute Regeln",
      regional_li3: "Kategorien u. a.: Ausweise, Steuernummern, Bankkarten/Konten, Telefon, Postleitzahlen, Wirtschafts-ID",
      regional_line: "Nicht nur Mustererkennung — eine praxisnahe regionale Regelbibliothek.",
      workflow_title: "Schneller prüfen. Sicherer exportieren.",
      wf1_h: "Prüfung im Kontext",
      wf1_p: "Erkannte Treffer und Inhalt gemeinsam sehen, vor dem Export bestätigen oder anpassen.",
      wf2_h: "Stapelverarbeitung ähnlicher PDFs",
      wf2_p: "Bestätigte Redaktionen vom aktuellen Dokument auf ähnliche PDFs anwenden.",
      wf3_h: "Fokussiertes Audit-Panel",
      wf3_p: "Gruppierte Einträge mit Risikohinweisen — weniger Doppelarbeit, klarer Ablauf.",
      early_title: "Warum Early Access kostenlos ist",
      early_body:
        "PlainBytes Redactor ist in der Early-Adopter-Phase kostenlos. Wir validieren reale Workflows, verbessern die Erkennung und Stabilität mit Feedback von Profis.",
      early_c1: "Lokal-zuerst bleibt Grundprinzip.",
      early_c2: "Kern-Redaktion ohne Cloud-Upload.",
      early_c3: "Early User prägen Roadmap und Qualität.",
      early_note:
        "Keine Zusage dauerhafter Gratis-Features, absoluter Sicherheit oder formaler Compliance ohne Zertifikat.",
      rm_v10: "v1.0 (aktuell)",
      rm_v10_li1: "Kern-Workflow physischer Redaktion",
      rm_v10_li2: "12 UI-Sprachen",
      rm_v10_li3: "20+ regionale Regeln",
      rm_v10_li4: "Stapelverarbeitung",
      rm_v12: "v1.2 (geplant)",
      rm_v12_li1: "Offline-OCR für gescannte PDFs",
      rm_v12_li2: "Editor für eigene Regeln",
      rm_v15: "v1.5 (geplant)",
      rm_v15_li1: "Lokaler Audit-Report-Export",
      rm_v15_li2: "Mehr Prüf- und Review-Tools",
      rm_v20: "v2.0 (Vision)",
      rm_v20_li1: "Plattformübergreifend",
      rm_v20_li2: "Fortgeschrittene semantische Maskierung",
      foot_dl: "Download & Sicherheit",
      foot_store: "Microsoft Store",
      foot_vt: "VirusTotal-Scan (wenn verfügbar)",
      foot_sup: "Support & Feedback",
      foot_gh: "GitHub",
      foot_email: "Support-E-Mail",
      foot_doc: "Dokumentation",
      foot_quick: "Schnellstart",
      foot_privacy: "Datenschutz",
      copy: "© 2026 PlainBytes Studio. All rights reserved.",
      quickstart_title: "Schnellstart",
      quickstart_body:
        "Installation über den Microsoft Store oder Ihr Paket. PDF öffnen, Erkennung starten, im Audit-Panel prüfen, Redaktionen bestätigen, exportieren. Für Stapel: bestätigte Markierungen vom Basisdokument auf weitere Dateien anwenden. Siehe In-App-Hilfe und Regelzentrum.",
      privacy_title: "Datenschutzerklärung",
      privacy_body:
        "Die Kern-Redaktion verarbeitet PDFs lokal und sendet keine Dokumentinhalte an PlainBytes-Server. Ergänzen Sie vor Veröffentlichung rechtliche Angaben und Kontakt. Dieser Text ist ein Platzhalter und keine Rechtsberatung.",
    },
    fr: {
      brand: "PlainBytes Redactor",
      nav_home: "Accueil",
      nav_guide: "Guide utilisateur",
      nav_features: "Fonctionnalités",
      nav_regional: "Règions",
      nav_roadmap: "Feuille de route",
      nav_support: "Assistance",
      nav_download: "Obtenir sur le Microsoft Store",
      hero_kicker: "PlainBytes Redactor",
      hero_tagline: "Rédigez des PDF sans envoyer les données clients ailleurs.",
      hero_lead:
        "PlainBytes Redactor s'exécute entièrement sur votre ordinateur — pas d'envoi cloud, aucun service IA ne voit vos fichiers. Détection automatique pour les formats d'identifiants de 28 pays, plus revue manuelle avant export.",
      hero_cta_primary: "Obtenir sur le Microsoft Store",
      hero_cta_secondary: "Voir la démo",
      hero_badge_1: "100 % hors ligne",
      hero_badge_2: "Rédaction physique",
      hero_badge_3: "28 pays",
      hero_badge_4: "Revue manuelle",
      hero_note: "Essai gratuit 10 jours · Achat unique · Sans abonnement",
      hero_video: "Vidéo de démo (boucle 12–15 s) — remplacez par votre MP4 hébergé ou intégration.",
      trust_title: "Pourquoi le traitement reste local",
      trust_body_p1:
        "La plupart des outils de rédaction — surtout ceux basés sur l'IA — envoient vos documents sur un serveur avant de trouver et supprimer les informations sensibles. Pour quiconque est tenu par la confidentialité, le secret professionnel ou l'indépendance d'audit, c'est un risque inutile pour rédiger un fichier.",
      trust_body_p2:
        "PlainBytes Redactor effectue toute la détection et le traitement sur votre appareil. Vos fichiers ne quittent jamais votre ordinateur — pas de compte, pas de sync, pas de serveur.",
      section_how_title: "Fonctionnement",
      wf_kicker: "Fonctionnement",
      wf_title: "Du fichier ouvert à l'export rédigé",
      wf_step1_title: "Ouvrir et analyser",
      wf_step1_desc: "Chargez un PDF et lancez la détection pour les formats de votre région.",
      wf_step2_title: "Vérifier les signalements",
      wf_step2_desc: "Consultez chaque élément signalé avec sa catégorie de risque.",
      wf_step3_title: "Ajuster manuellement",
      wf_step3_desc: "Ajoutez, supprimez ou affinez avant de finaliser.",
      wf_step4_title: "Exporter",
      wf_step4_desc: "Contenu et métadonnées supprimés définitivement.",
      how_li1:
        "Détection automatique — Noms, numéros d'identité, téléphones, adresses et comptes financiers dans 28 formats pays, sans repartir de zéro.",
      how_li2:
        "Panneau de revue manuelle — Vérifiez chaque élément signalé avant export. Ajoutez, supprimez ou ajustez — l'automatisation est un point de départ, pas le mot final.",
      how_li3:
        "Suppression réelle, pas masquage — Le contenu est retiré du fichier, pas seulement masqué. Les métadonnées sensibles sont aussi supprimées.",
      how_li4: "Traitement par lots — Appliquez les mêmes règles à plusieurs fichiers.",
      scenarios_title: "Conçu pour le travail des praticiens solo",
      scenario_attorney_label: "Pour les avocats",
      scenario_attorney_body:
        "Rédigez SSN, données financières et autres PII avant e-filing ou partage discovery, sans passer par un cloud tiers.",
      scenario_accountant_label: "Pour les comptables",
      scenario_accountant_body:
        "Rédigez numéros de compte, SSN et détails financiers clients avant de partager papiers de travail d'audit, déclarations fiscales ou rapports de fin d'année — sans passer par un cloud tiers.",
      scenario_hr_label: "Pour les équipes RH",
      scenario_hr_body:
        "Rédigez salaires, SSN et données personnelles avant de partager lettres d'offre, dossiers de licenciement ou fichiers du personnel avec auditeurs, conseils juridiques ou en réponse à des demandes de données.",
      scenario_attorney:
        "Pour les avocats — Rédigez SSN, données financières et autres PII avant e-filing ou partage discovery, sans passer par un cloud tiers.",
      scenario_accountant:
        "Pour les comptables — Rédigez numéros de compte, SSN et détails financiers clients avant de partager papiers de travail d'audit, déclarations fiscales ou rapports de fin d'année, sans passer par un cloud tiers.",
      included_title: "Inclus aujourd'hui",
      included_li1: "Rédaction physique",
      included_li2: "Interface en 12 langues",
      included_li3: "Règles pour 28 pays",
      included_li4: "Traitement par lots",
      pricing_title: "Tarifs",
      pricing_body:
        "Essayez toutes les fonctions gratuitement pendant 10 jours. Ensuite, un paiement unique de $34 débloque la version complète — sans abonnement ni frais récurrents.",
      trust_tag1: "Pas d’envoi cloud",
      trust_tag2: "Inférence IA hors ligne",
      trust_tag3: "Export de rédaction physique",
      pillar1_h: "Traitement 100 % hors ligne",
      pillar1_p:
        "Sans compte ni envoi de documents. IA, règles et rendu locaux, utilisables hors connexion.",
      pillar2_h: "Export de rédaction physique",
      pillar2_p:
        "Au-delà du masquage visuel : PDF rédigés physiquement et métadonnées courantes réduites pour limiter les risques lors du partage et de l’archivage.",
      pillar3_h: "IA locale + règions",
      pillar3_p:
        "IA multilingue locale pour noms, organisations et lieux, avec règles régionales pour pièces d’identité, téléphones, cartes, identifiants fiscaux, etc.",
      section_everything: "Tout ce dont vous avez besoin",
      section_everything_lead: "Détecter, vérifier, rédiger et exporter — le tout hors ligne.",
      everything_li1: "Piste d’audit côte à côte : éléments groupés et indices de risque clairs",
      everything_li2: "Export de rédaction physique — contenu retiré des flux, pas seulement masqué",
      everything_li3: "IA locale et plus de 145 règles régionales intégrées pour les données structurées",
      everything_li4: "Lots : appliquer les marques confirmées d’un PDF de référence à des fichiers similaires",
      everything_li5: "100 % privé — pas de cloud, pas d’envois, strictement hors ligne",
      everything_li6: "Interface en 12 langues · rendu natif rapide · export attentif aux métadonnées",
      regional_title: "Règles de détection régionales intégrées",
      regional_intro: "Parcourez la couverture par grandes régions et types de documents.",
      regional_li1: "Plus de 20 régions",
      regional_li2: "Plus de 145 règles intégrées",
      regional_li3: "Catégories : pièces d’identité, fiscalité, cartes bancaires/comptes, téléphone, codes postaux, identifiants d’entreprise",
      regional_line: "Pas seulement des motifs — une bibliothèque régionale pensée pour la revue réelle.",
      workflow_title: "Revoir plus vite. Exporter plus sûrement.",
      wf1_h: "Revue côte à côte",
      wf1_p: "Voir les éléments détectés et le document ensemble, puis confirmer avant export.",
      wf2_h: "Traitement par lots",
      wf2_p: "Appliquer les rédactions validées du document courant à des PDF similaires.",
      wf3_h: "Panneau d’audit ciblé",
      wf3_p: "Regroupement des éléments sensibles avec indices de risque, moins de confirmations dupliquées.",
      early_title: "Pourquoi gratuit en accès anticipé",
      early_body:
        "PlainBytes Redactor est gratuit pendant la phase early adopter. Nous validons les usages réels, améliorons la détection et la stabilité grâce aux retours professionnels.",
      early_c1: "L’architecture local-first reste un principe fondateur.",
      early_c2: "Les flux de rédaction essentiels ne reposent pas sur le cloud.",
      early_c3: "Les premiers utilisateurs façonnent la feuille de route et la qualité.",
      early_note:
        "Nous ne promettons ni gratuité permanente de toutes les fonctions, ni sécurité absolue, ni conformité formelle non certifiée.",
      rm_v10: "v1.0 (actuel)",
      rm_v10_li1: "Flux de rédaction physique principal",
      rm_v10_li2: "Interface en 12 langues",
      rm_v10_li3: "Couverture 20+ régions",
      rm_v10_li4: "Traitement par lots",
      rm_v12: "v1.2 (prévu)",
      rm_v12_li1: "OCR hors ligne pour PDF numérisés",
      rm_v12_li2: "Éditeur de règles personnalisées",
      rm_v15: "v1.5 (prévu)",
      rm_v15_li1: "Export de rapport d’audit local",
      rm_v15_li2: "Plus d’outils de vérification",
      rm_v20: "v2.0 (vision)",
      rm_v20_li1: "Multi-plateforme",
      rm_v20_li2: "Masquage sémantique avancé",
      foot_dl: "Téléchargement et sécurité",
      foot_store: "Microsoft Store",
      foot_vt: "Analyse VirusTotal (si disponible)",
      foot_sup: "Support et commentaires",
      foot_gh: "GitHub",
      foot_email: "E-mail d’assistance",
      foot_doc: "Documentation",
      foot_quick: "Guide de démarrage",
      foot_privacy: "Politique de confidentialité",
      copy: "© 2026 PlainBytes Studio. Tous droits réservés.",
      quickstart_title: "Guide de démarrage",
      quickstart_body:
        "Installez depuis le Microsoft Store ou votre package. Ouvrez un PDF, lancez la détection, vérifiez dans le panneau d’audit, confirmez puis exportez. Pour le lot : appliquez les marques validées du document de référence. Voir l’aide intégrée et le centre de règles.",
      privacy_title: "Politique de confidentialité",
      privacy_body:
        "Le flux de rédaction principal traite les PDF sur votre appareil sans envoyer le contenu des documents aux serveurs PlainBytes. Complétez les informations légales avant publication. Ce texte est un placeholder et ne constitue pas un conseil juridique.",
    },
  };

  STR["zh-Hant"] = {
    ...STR.zh,
    nav_home: "首頁",
    nav_guide: "使用手冊",
    nav_features: "功能",
    nav_regional: "區域規則",
    nav_roadmap: "路線圖",
    nav_support: "支援",
    nav_download: "在 Microsoft Store 取得",
    hero_tagline: "脫敏 PDF，客戶資料無需離開本機。",
    hero_lead:
      "PlainBytes Redactor 完全在您的電腦上運行——不上傳雲端，沒有 AI 服務查看您的檔案。支援 28 國/地區識別碼格式的自動偵測，匯出前可人工複核。",
    hero_cta_secondary: "觀看演示",
    hero_badge_3: "28 國/地區",
    hero_badge_4: "人工複核",
    hero_note: "10 天全功能免費試用 · 一次性購買 · 無訂閱",
    trust_title: "為什麼處理必須留在本地",
    trust_body_p1:
      "大多數脫敏工具——尤其是 AI 驅動的——需要先把文件上傳到伺服器才能查找並刪除敏感資訊。對受保密義務、特權規則或審計獨立性約束的人而言，僅為脫敏一份文件就承擔這種風險並不合理。",
    trust_body_p2:
      "PlainBytes Redactor 在您自己的裝置上完成全部偵測與處理。檔案不會離開您的電腦，無需帳號、無需同步、也沒有伺服器參與。",
    section_how_title: "工作原理",
    wf_kicker: "工作原理",
    wf_title: "從開啟檔案到脫敏匯出",
    wf_step1_title: "開啟並掃描",
    wf_step1_desc: "載入 PDF，依您所在地區的格式執行偵測。",
    wf_step2_title: "複核標記",
    wf_step2_desc: "查看每項標記及其風險類別。",
    wf_step3_title: "手動調整",
    wf_step3_desc: "定稿前可新增、刪除或微調。",
    wf_step4_title: "匯出",
    wf_step4_desc: "內容與中繼資料永久移除。",
    how_li1:
      "自動偵測 — 識別 28 國/地區格式下的姓名、證件號、電話、地址與金融帳號，無需從零開始。",
    how_li2:
      "人工複核面板 — 匯出前逐項檢查標記結果，可手動新增、刪除或調整脫敏區域；自動化是起點，不是最終結論。",
    how_li3:
      "真正刪除，而非遮蓋 — 從 PDF 底層移除敏感內容，而非僅加黑框；同時清理可能洩露資訊的中繼資料。",
    how_li4: "批次處理 — 將同一套規則一次性套用到多個檔案。",
    scenarios_title: "為個體執業者的實際工作方式而設計",
    scenario_attorney_label: "律師",
    scenario_attorney_body:
      "在電子提交或共享證據材料前，脫敏社安號、財務資訊及其他 PII，無需將客戶檔案經第三方雲服務中轉。",
    scenario_accountant_label: "會計師",
    scenario_accountant_body:
      "在共享審計工作底稿、稅務申報或年終報告前，脫敏帳號、社安號及客戶財務細節，無需將客戶資料經第三方雲服務中轉。",
    scenario_hr_label: "人力資源團隊",
    scenario_hr_body:
      "與審計師、法律顧問共享或回應資料請求前，脫敏錄用函、離職紀錄或人事檔案中的薪資、社安號及個人細節。",
    scenario_attorney:
      "律師 — 在電子提交或共享證據材料前，脫敏社安號、財務資訊及其他 PII，無需將客戶檔案經第三方雲服務中轉。",
    scenario_accountant:
      "會計師 — 在共享審計工作底稿、稅務申報或年終報告前，脫敏帳號、社安號及客戶財務細節，無需將客戶資料經第三方雲服務中轉。",
    included_title: "目前包含的功能",
    included_li1: "物理脫敏",
    included_li2: "12 種介面語言",
    included_li3: "28 國/地區規則覆蓋",
    included_li4: "批次處理",
    pricing_title: "定價",
    pricing_body: "10 天免費試用全部功能。之後一次性支付 $34 解鎖完整版——無訂閱、無週期性費用。",
    workflow_title: "複核更快，匯出更穩",
    early_title: "為何早期存取免費",
    foot_quick: "快速入門",
    foot_privacy: "隱私政策",
    quickstart_title: "快速入門",
    privacy_title: "隱私政策",
    copy: "© 2026 PlainBytes Studio. 保留所有權利。",
  };

  STR.ko = {
    ...STR.en,
    nav_home: "홈",
    nav_guide: "사용자 가이드",
    nav_features: "기능",
    nav_regional: "지역 규칙",
    nav_roadmap: "로드맵",
    nav_support: "지원",
    nav_download: "Microsoft Store에서 받기",
    hero_kicker: "PlainBytes Redactor",
    hero_tagline: "고객 데이터를 외부로 보내지 않고 PDF를 비식별화합니다.",
    hero_lead:
      "PlainBytes Redactor는 전부 사용자 PC에서 실행됩니다. 클라우드 업로드 없음, AI 서비스가 파일을 보지 않습니다. 28개국 식별자 형식 자동 탐지와 내보내기 전 수동 검토를 지원합니다.",
    hero_cta_secondary: "데모 보기",
    hero_badge_3: "28개국",
    hero_badge_4: "수동 검토",
    hero_note: "10일 전 기능 무료 체험 · 일회성 구매 · 구독 없음",
    trust_title: "처리가 로컬에 머무는 이유",
    trust_body_p1:
      "대부분의 비식별화 도구, 특히 AI 기반 도구는 민감 정보를 찾아 제거하기 전에 문서를 서버에 업로드합니다. 비밀 유지, 특권, 감사 독립성 규칙에 묶인 사람에게 파일 하나를 비식별화하기 위해 그런 위험을 감수할 필요는 없습니다.",
    trust_body_p2:
      "PlainBytes Redactor는 탐지와 처리를 모두 사용자 기기에서 수행합니다. 파일은 PC를 떠나지 않으며, 계정·동기화·서버가 필요 없습니다.",
    section_how_title: "작동 방식",
    wf_kicker: "작동 방식",
    wf_title: "파일 열기부터 편집보내기까지",
    wf_step1_title: "열기 및 스캔",
    wf_step1_desc: "PDF를 불러와 해당 지역 형식으로 탐지를 실행합니다.",
    wf_step2_title: "플래그 검토",
    wf_step2_desc: "위험 범주와 함께 표시된 모든 항목을 확인합니다.",
    wf_step3_title: "수동 조정",
    wf_step3_desc: "확정 전에 추가·삭제·미세 조정이 가능합니다.",
    wf_step4_title: "보내기",
    wf_step4_desc: "콘텐츠와 메타데이터가 영구적으로 제거됩니다.",
    how_li1:
      "자동 탐지 — 28개국 형식의 이름, 신분증 번호, 전화, 주소, 금융 계좌 번호를 식별합니다. 처음부터 시작할 필요가 없습니다.",
    how_li2:
      "수동 검토 패널 — 내보내기 전에 표시된 항목을 모두 확인합니다. 추가·삭제·조정 가능 — 자동화는 출발점이지 최종 결정이 아닙니다.",
    how_li3:
      "가림이 아닌 실제 삭제 — 검은 상자가 아니라 PDF 본문에서 내용을 제거합니다. 민감 정보를 노출할 수 있는 메타데이터도 정리합니다.",
    how_li4: "일괄 처리 — 동일 규칙을 여러 파일에 한 번에 적용합니다.",
    scenarios_title: "1인 실무자의 실제 업무 방식에 맞춤",
    scenario_attorney_label: "변호사용",
    scenario_attorney_body:
      "전자 제출이나 디스커버리 공유 전에 SSN, 재무 정보 및 기타 PII를 비식별화합니다. 고객 파일을 제3자 클라우드로 보내지 않습니다.",
    scenario_accountant_label: "회계사용",
    scenario_accountant_body:
      "감사 조서, 세무 신고 또는 연말 보고서를 공유하기 전에 계좌 번호, SSN 및 고객 재무 정보를 비식별화합니다. 고객 데이터를 제3자 클라우드로 보내지 않습니다.",
    scenario_hr_label: "HR 팀용",
    scenario_hr_body:
      "감사인, 법무 담당자와 공유하거나 데이터 요청에 응답하기 전에 채용 제안서, 퇴직 기록 또는 인사 파일에서 급여, SSN 및 개인 정보를 비식별화합니다.",
    scenario_attorney:
      "변호사용 — 전자 제출이나 디스커버리 공유 전에 SSN, 재무 정보 및 기타 PII를 비식별화합니다. 고객 파일을 제3자 클라우드로 보내지 않습니다.",
    scenario_accountant:
      "회계사용 — 감사 조서, 세무 신고 또는 연말 보고서를 공유하기 전에 계좌 번호, SSN 및 고객 재무 정보를 비식별화합니다. 고객 데이터를 제3자 클라우드로 보내지 않습니다.",
    included_title: "현재 포함된 기능",
    included_li1: "물리적 비식별화",
    included_li2: "12개 언어 UI",
    included_li3: "28개국 규칙 지원",
    included_li4: "배치 처리",
    pricing_title: "가격",
    pricing_body:
      "10일간 모든 기능을 무료로 체험하세요. 이후 $34 일회 결제로 전체 버전 이용 — 구독이나 정기 요금 없음.",
    trust_tag1: "클라우드 업로드 없음",
    trust_tag2: "오프라인 AI 추론",
    trust_tag3: "물리적 비식별화 내보내기",
    pillar1_h: "100% 오프라인 처리",
    pillar1_p:
      "계정이 필요 없고 문서 업로드도 없습니다. AI 추론, 규칙 매칭, 렌더링이 로컬에서 동작합니다.",
    pillar2_h: "물리적 비식별화 내보내기",
    pillar2_p:
      "시각적 가림을 넘어 PDF 콘텐츠 스트림에서 민감 정보를 제거하고 메타데이터 흔적을 줄입니다.",
    pillar3_h: "온디바이스 AI + 지역 규칙",
    pillar3_p:
      "이름·기관·지명을 로컬 다국어 AI로 탐지하고, 신분증·전화·카드·세금 식별자 규칙과 결합합니다.",
    section_everything: "필요한 모든 기능",
    section_everything_lead: "탐지, 검토, 비식별화, 내보내기 — 모두 오프라인.",
    everything_li1: "그룹화와 위험 신호가 포함된 나란히 감사 추적",
    everything_li2: "물리적 비식별화 내보내기 — 단순 가림이 아닌 콘텐츠 제거",
    everything_li3: "구조화 데이터용 145+ 내장 지역 규칙과 온디바이스 AI",
    everything_li4: "기준 PDF의 확정 마크를 유사 파일에 적용하는 배치 처리",
    everything_li5: "100% 프라이빗 — 클라우드 없음, 업로드 없음",
    everything_li6: "12개 언어 UI · 빠른 네이티브 렌더링 · 메타데이터 인식 내보내기",
    regional_title: "내장 지역 탐지 규칙",
    regional_intro: "주요 지역과 문서 유형별 내장 탐지 범위를 확인하세요.",
    regional_li1: "20+ 지역 지원",
    regional_li2: "145+ 내장 규칙",
    regional_li3: "신분증, 세금번호, 카드/계좌, 전화, 우편번호, 사업자 식별자 등",
    regional_line: "단순 패턴 매칭이 아닌 실제 검토를 위한 지역 규칙 라이브러리",
    workflow_title: "더 빠르게 검토하고 더 안전하게 내보내기",
    wf1_h: "나란히 검토",
    wf1_p: "탐지 항목과 문서 내용을 함께 확인하고 내보내기 전 결과를 조정합니다.",
    wf2_h: "유사 PDF 배치 처리",
    wf2_p: "현재 문서의 확정 결과를 유사 PDF에 적용해 일괄 처리합니다.",
    wf3_h: "집중형 감사 추적 패널",
    wf3_p: "민감 항목을 그룹으로 검토해 중복 확인을 줄이고 흐름을 단순화합니다.",
    early_title: "얼리 액세스 기간 무료 제공 이유",
    early_body:
      "실제 업무 흐름 검증, 다지역·다형식 탐지 품질 개선, 안정성 향상을 위해 얼리 어답터 기간에 무료로 제공합니다.",
    early_c1: "로컬 우선 아키텍처는 제품의 핵심 원칙으로 유지됩니다.",
    early_c2: "핵심 비식별화 흐름은 클라우드 업로드에 의존하지 않습니다.",
    early_c3: "초기 사용자 피드백이 로드맵과 품질 기준을 만듭니다.",
    early_note: "향후 모든 기능의 영구 무료, 절대 보안, 미보유 인증을 약속하지 않습니다.",
    rm_v10: "v1.0 (현재)",
    rm_v10_li1: "핵심 물리적 비식별화 워크플로",
    rm_v10_li2: "12개 언어 UI",
    rm_v10_li3: "20+ 지역 규칙",
    rm_v10_li4: "배치 처리",
    rm_v12: "v1.2 (계획)",
    rm_v12_li1: "스캔 PDF용 오프라인 OCR",
    rm_v12_li2: "사용자 정의 규칙 편집기",
    rm_v15: "v1.5 (계획)",
    rm_v15_li1: "로컬 감사 리포트 내보내기",
    rm_v15_li2: "검증/리뷰 도구 강화",
    rm_v20: "v2.0 (비전)",
    rm_v20_li1: "크로스 플랫폼",
    rm_v20_li2: "고급 의미 기반 마스킹",
    foot_dl: "다운로드 및 보안",
    foot_sup: "지원 및 피드백",
    foot_email: "지원 이메일",
    foot_doc: "문서",
    foot_quick: "빠른 시작",
    foot_privacy: "개인정보 처리방침",
    quickstart_title: "빠른 시작",
    quickstart_body:
      "Microsoft Store 또는 배포 패키지에서 설치합니다. PDF를 열고 탐지를 실행한 뒤 감사 패널에서 확인하고 내보냅니다. 배치 작업은 기준 문서의 확정 마크를 다른 파일에 적용할 수 있습니다.",
    privacy_title: "개인정보 처리방침",
    privacy_body:
      "핵심 비식별화 흐름은 문서를 서버로 전송하지 않고 기기에서 처리되도록 설계되었습니다. 배포 전 법적 주체 정보와 연락처를 정책 페이지에 반영하세요.",
  };

  STR.pt = {
    ...STR.en,
    nav_home: "Início",
    nav_guide: "Guia do usuário",
    nav_features: "Recursos",
    nav_regional: "Regras regionais",
    nav_roadmap: "Roteiro",
    nav_support: "Suporte",
    nav_download: "Baixar na Microsoft Store",
    hero_kicker: "PlainBytes Redactor",
    hero_tagline: "Redija PDFs sem enviar dados de clientes para lugar nenhum.",
    hero_lead:
      "PlainBytes Redactor roda inteiramente no seu computador — sem upload na nuvem, nenhum serviço de IA vê seus arquivos. Detecção automática para formatos de identificadores de 28 países, mais revisão manual antes de exportar.",
    hero_cta_secondary: "Ver demonstração",
    hero_badge_3: "28 países",
    hero_badge_4: "Revisão manual",
    hero_note: "Teste grátis de 10 dias · Compra única · Sem assinatura",
    trust_title: "Por que o processamento fica local",
    trust_body_p1:
      "A maioria das ferramentas de redação — especialmente as com IA — envia seus documentos a um servidor antes de encontrar e remover informações sensíveis. Para quem está sujeito a confidencialidade, privilégio ou independência de auditoria, esse risco não deveria ser necessário só para redigir um arquivo.",
    trust_body_p2:
      "PlainBytes Redactor faz toda a detecção e processamento no seu dispositivo. Seus arquivos nunca saem do computador — sem conta, sem sync, sem servidor.",
    section_how_title: "Como funciona",
    wf_kicker: "Como funciona",
    wf_title: "Do arquivo aberto à exportação redigida",
    wf_step1_title: "Abrir e analisar",
    wf_step1_desc: "Carregue um PDF e execute a detecção para os formatos da sua região.",
    wf_step2_title: "Revisar sinalizações",
    wf_step2_desc: "Veja cada item sinalizado com sua categoria de risco.",
    wf_step3_title: "Ajustar manualmente",
    wf_step3_desc: "Adicione, remova ou refine antes de finalizar.",
    wf_step4_title: "Exportar",
    wf_step4_desc: "Conteúdo e metadados removidos permanentemente.",
    how_li1:
      "Detecção automática — Nomes, números de ID, telefones, endereços e contas financeiras em 28 formatos de países, sem começar do zero.",
    how_li2:
      "Painel de revisão manual — Verifique cada item sinalizado antes de exportar. Adicione, remova ou ajuste — a automação é o ponto de partida, não a palavra final.",
    how_li3:
      "Remoção real, não mascaramento — O conteúdo é retirado do arquivo, não apenas coberto. Metadados sensíveis também são removidos.",
    how_li4: "Processamento em lote — Aplique as mesmas regras a vários arquivos de uma vez.",
    scenarios_title: "Feito para a rotina de profissionais autônomos",
    scenario_attorney_label: "Para advogados",
    scenario_attorney_body:
      "Redija SSN, dados financeiros e outros PII antes de e-filing ou compartilhamento discovery, sem passar arquivos de clientes por nuvem de terceiros.",
    scenario_accountant_label: "Para contadores",
    scenario_accountant_body:
      "Redija números de conta, SSN e detalhes financeiros de clientes antes de compartilhar papéis de trabalho de auditoria, declarações fiscais ou relatórios de fim de ano — sem passar dados de clientes por nuvem de terceiros.",
    scenario_hr_label: "Para equipes de RH",
    scenario_hr_body:
      "Redija valores salariais, SSN e dados pessoais antes de compartilhar cartas de oferta, registros de desligamento ou arquivos de pessoal com auditores, assessoria jurídica ou em resposta a solicitações de dados.",
    scenario_attorney:
      "Para advogados — Redija SSN, dados financeiros e outros PII antes de e-filing ou compartilhamento discovery, sem passar arquivos de clientes por nuvem de terceiros.",
    scenario_accountant:
      "Para contadores — Redija números de conta, SSN e detalhes financeiros de clientes antes de compartilhar papéis de trabalho de auditoria, declarações fiscais ou relatórios de fim de ano, sem passar dados de clientes por nuvem de terceiros.",
    included_title: "O que está incluído hoje",
    included_li1: "Redação física",
    included_li2: "Interface em 12 idiomas",
    included_li3: "Regras para 28 países",
    included_li4: "Processamento em lote",
    pricing_title: "Preços",
    pricing_body:
      "Experimente todos os recursos grátis por 10 dias. Depois, pagamento único de $34 desbloqueia a versão completa — sem assinatura nem taxas recorrentes.",
    pillar1_h: "Processamento 100% offline",
    pillar2_h: "Exportação com redação física",
    pillar3_h: "IA no dispositivo + regras regionais",
    section_everything: "Tudo o que você precisa",
    section_everything_lead: "Detectar, revisar, redigir e exportar — tudo offline.",
    everything_li1: "Trilha de auditoria lado a lado com itens agrupados e sinais de risco",
    everything_li2: "Redação física no PDF: remove conteúdo do stream, não só cobertura visual",
    everything_li3: "145+ regras regionais integradas e IA local para dados estruturados",
    everything_li4: "Lotes: aplicar marcações confirmadas do PDF base em arquivos similares",
    everything_li5: "100% privado — sem nuvem, sem uploads",
    everything_li6: "UI em 12 idiomas · renderização nativa rápida · exportação com foco em metadados",
    regional_title: "Regras regionais de detecção integradas",
    regional_intro: "Veja a cobertura por região e tipo de documento.",
    workflow_title: "Revise mais rápido. Exporte com segurança.",
    wf1_h: "Revisão lado a lado",
    wf2_h: "Processamento em lote para PDFs similares",
    wf3_h: "Painel de auditoria focado",
    early_title: "Por que é gratuito no acesso antecipado",
    early_body:
      "Durante a fase early adopter, o foco é validar fluxos reais, melhorar a qualidade de detecção e elevar a estabilidade com feedback profissional.",
    early_c1: "A arquitetura local-first continuará como princípio central do produto.",
    early_c2: "O fluxo principal de redação não depende de upload para a nuvem.",
    early_c3: "Usuários iniciais ajudam a definir roadmap e baseline de qualidade.",
    early_note:
      "Não prometemos acesso gratuito permanente a todos os recursos futuros, segurança absoluta ou certificações formais não obtidas.",
    rm_v10: "v1.0 (Atual)",
    rm_v10_li1: "Fluxo principal de redação física",
    rm_v10_li2: "Interface em 12 idiomas",
    rm_v10_li3: "Cobertura de 20+ regiões",
    rm_v10_li4: "Processamento em lote",
    rm_v12: "v1.2 (Planejado)",
    rm_v12_li1: "OCR offline para PDFs digitalizados",
    rm_v12_li2: "Editor de regras personalizadas",
    rm_v15: "v1.5 (Planejado)",
    rm_v15_li1: "Exportação local de relatório de auditoria",
    rm_v15_li2: "Mais ferramentas de verificação e revisão",
    rm_v20: "v2.0 (Visão)",
    rm_v20_li1: "Suporte multiplataforma",
    rm_v20_li2: "Fluxos avançados de mascaramento semântico",
    foot_sup: "Suporte e feedback",
    foot_email: "E-mail de suporte",
    foot_quick: "Guia rápido",
    foot_privacy: "Política de privacidade",
    quickstart_title: "Guia rápido",
    quickstart_body:
      "Instale pela Microsoft Store ou pacote distribuído. Abra um PDF, execute a detecção, revise no painel de auditoria, confirme e exporte.",
    privacy_title: "Política de privacidade",
    privacy_body:
      "O fluxo principal de redação processa os PDFs localmente e não envia conteúdo de documentos para os servidores PlainBytes.",
  };

  STR.it = {
    ...STR.en,
    nav_home: "Home",
    nav_guide: "Guida utente",
    nav_features: "Funzionalità",
    nav_regional: "Regole regionali",
    nav_roadmap: "Roadmap",
    nav_support: "Supporto",
    nav_download: "Ottieni da Microsoft Store",
    hero_kicker: "PlainBytes Redactor",
    hero_tagline: "Oscura PDF senza inviare i dati dei clienti altrove.",
    hero_lead:
      "PlainBytes Redactor funziona interamente sul tuo computer — nessun upload cloud, nessun servizio IA vede i tuoi file. Rilevamento automatico per formati di identificatori di 28 paesi, più revisione manuale prima dell'export.",
    hero_cta_secondary: "Guarda la demo",
    hero_badge_3: "28 paesi",
    hero_badge_4: "Revisione manuale",
    hero_note: "Prova gratuita 10 giorni · Acquisto una tantum · Nessun abbonamento",
    trust_title: "Perché l'elaborazione resta locale",
    trust_body_p1:
      "La maggior parte degli strumenti di redazione — soprattutto quelli basati su IA — carica i documenti su un server prima di trovare e rimuovere le informazioni sensibili. Per chi è vincolato da riservatezza, privilegio o indipendenza di audit, non dovrebbe essere un rischio necessario solo per redigere un file.",
    trust_body_p2:
      "PlainBytes Redactor esegue rilevamento ed elaborazione sul tuo dispositivo. I file non lasciano mai il computer — nessun account, sync o server.",
    section_how_title: "Come funziona",
    wf_kicker: "Come funziona",
    wf_title: "Dal file aperto all'export redatto",
    wf_step1_title: "Apri e analizza",
    wf_step1_desc: "Carica un PDF ed esegui il rilevamento per i formati della tua regione.",
    wf_step2_title: "Rivedi i flag",
    wf_step2_desc: "Visualizza ogni elemento segnalato con la relativa categoria di rischio.",
    wf_step3_title: "Regola manualmente",
    wf_step3_desc: "Aggiungi, rimuovi o perfeziona prima di finalizzare.",
    wf_step4_title: "Esporta",
    wf_step4_desc: "Contenuto e metadati rimossi in modo permanente.",
    how_li1:
      "Rilevamento automatico — Nomi, numeri ID, telefoni, indirizzi e conti finanziari in 28 formati nazionali, senza partire da zero.",
    how_li2:
      "Pannello di revisione manuale — Controlla ogni elemento segnalato prima dell'export. Aggiungi, rimuovi o modifica — l'automazione è un punto di partenza, non la parola finale.",
    how_li3:
      "Rimozione reale, non mascheramento — Il contenuto viene rimosso dal file, non solo coperto. Anche i metadati sensibili vengono eliminati.",
    how_li4: "Elaborazione batch — Applica le stesse regole a più file contemporaneamente.",
    scenarios_title: "Progettato per il lavoro dei professionisti in solo practice",
    scenario_attorney_label: "Per avvocati",
    scenario_attorney_body:
      "Oscura SSN, dati finanziari e altri PII prima di e-filing o condivisione discovery, senza passare i file dei clienti per cloud di terze parti.",
    scenario_accountant_label: "Per commercialisti",
    scenario_accountant_body:
      "Oscura numeri di conto, SSN e dettagli finanziari dei clienti prima di condividere working paper di audit, dichiarazioni fiscali o report di fine anno — senza passare i dati dei clienti per cloud di terze parti.",
    scenario_hr_label: "Per team HR",
    scenario_hr_body:
      "Oscura cifre salariali, SSN e dati personali prima di condividere lettere di offerta, registri di cessazione o fascicoli del personale con revisori, consulenti legali o in risposta a richieste di dati.",
    scenario_attorney:
      "Per avvocati — Oscura SSN, dati finanziari e altri PII prima di e-filing o condivisione discovery, senza passare i file dei clienti per cloud di terze parti.",
    scenario_accountant:
      "Per commercialisti — Oscura numeri di conto, SSN e dettagli finanziari dei clienti prima di condividere working paper di audit, dichiarazioni fiscali o report di fine anno, senza passare i dati dei clienti per cloud di terze parti.",
    included_title: "Cosa è incluso oggi",
    included_li1: "Redazione fisica",
    included_li2: "Interfaccia in 12 lingue",
    included_li3: "Regole per 28 paesi",
    included_li4: "Elaborazione batch",
    pricing_title: "Prezzi",
    pricing_body:
      "Prova tutte le funzioni gratis per 10 giorni. Poi un pagamento unico di $34 sblocca la versione completa — nessun abbonamento né costi ricorrenti.",
    pillar1_h: "Elaborazione 100% offline",
    pillar2_h: "Export con redazione fisica",
    pillar3_h: "IA locale + regole regionali",
    section_everything: "Tutto ciò che ti serve",
    section_everything_lead: "Rileva, rivedi, oscura ed esporta — tutto offline.",
    everything_li1: "Traccia di audit affiancata con elementi raggruppati e indicatori di rischio chiari",
    everything_li2: "Export con redazione fisica — i contenuti sensibili vengono rimossi dal PDF, non solo coperti",
    everything_li3: "IA sul dispositivo e oltre 145 regole regionali integrate per dati strutturati",
    everything_li4: "Batch: applica le marcature confermate dal PDF base ai file simili",
    everything_li5: "100% privato — niente cloud, niente upload",
    everything_li6: "Interfaccia in 12 lingue · rendering nativo veloce · export attento ai metadati",
    regional_title: "Regole di rilevamento regionali integrate",
    workflow_title: "Rivedi più velocemente. Esporta in sicurezza.",
    wf1_h: "Revisione affiancata",
    wf2_h: "Elaborazione batch di PDF simili",
    wf3_h: "Pannello audit focalizzato",
    early_title: "Perché gratuito durante l'accesso anticipato",
    early_body:
      "Durante la fase early adopter il prodotto è gratuito per validare i flussi reali, migliorare la qualità di rilevamento e aumentare la stabilità.",
    early_c1: "L'architettura local-first resta un principio fondamentale del prodotto.",
    early_c2: "Il flusso principale di redazione non dipende da upload cloud.",
    early_c3: "Gli utenti iniziali contribuiscono a roadmap e baseline di qualità.",
    early_note:
      "Non promettiamo accesso gratuito permanente a tutte le funzioni future, sicurezza assoluta o certificazioni non ottenute.",
    rm_v10: "v1.0 (Attuale)",
    rm_v10_li1: "Flusso principale di redazione fisica",
    rm_v10_li2: "Interfaccia in 12 lingue",
    rm_v10_li3: "Copertura di oltre 20 regioni",
    rm_v10_li4: "Elaborazione batch",
    rm_v12: "v1.2 (Pianificato)",
    rm_v12_li1: "OCR offline per PDF scansionati",
    rm_v12_li2: "Editor di regole personalizzate",
    rm_v15: "v1.5 (Pianificato)",
    rm_v15_li1: "Esportazione locale del report di audit",
    rm_v15_li2: "Più strumenti di verifica e revisione",
    rm_v20: "v2.0 (Visione)",
    rm_v20_li1: "Supporto multipiattaforma",
    rm_v20_li2: "Mascheramento semantico avanzato",
    foot_sup: "Supporto e feedback",
    foot_email: "Email di supporto",
    foot_quick: "Guida rapida",
    foot_privacy: "Informativa sulla privacy",
    quickstart_title: "Guida rapida",
    quickstart_body:
      "Installa da Microsoft Store o dal pacchetto distribuito. Apri un PDF, avvia il rilevamento, rivedi nel pannello audit, conferma ed esporta.",
    privacy_title: "Informativa sulla privacy",
    privacy_body:
      "Il flusso di redazione principale elabora i PDF localmente e non invia contenuti dei documenti ai server PlainBytes.",
  };

  STR.es = {
    ...STR.en,
    nav_home: "Inicio",
    nav_guide: "Guía de usuario",
    nav_features: "Funciones",
    nav_regional: "Reglas regionales",
    nav_roadmap: "Hoja de ruta",
    nav_support: "Soporte",
    nav_download: "Obtener en Microsoft Store",
    hero_kicker: "PlainBytes Redactor",
    hero_tagline: "Redacta PDF sin enviar datos de clientes a ningún sitio.",
    hero_lead:
      "PlainBytes Redactor funciona íntegramente en tu ordenador — sin subida a la nube, ningún servicio de IA ve tus archivos. Detección automática para formatos de identificadores de 28 países, más revisión manual antes de exportar.",
    hero_cta_secondary: "Ver demo",
    hero_badge_3: "28 países",
    hero_badge_4: "Revisión manual",
    hero_note: "Prueba gratis 10 días · Compra única · Sin suscripción",
    trust_title: "Por qué el procesamiento permanece local",
    trust_body_p1:
      "La mayoría de herramientas de redacción — especialmente las basadas en IA — suben tus documentos a un servidor antes de encontrar y eliminar información sensible. Para quienes están sujetos a confidencialidad, privilegio o independencia de auditoría, no debería ser un riesgo necesario solo para redactar un archivo.",
    trust_body_p2:
      "PlainBytes Redactor realiza toda la detección y el procesamiento en tu dispositivo. Tus archivos nunca salen del ordenador — sin cuenta, sin sync, sin servidor.",
    section_how_title: "Cómo funciona",
    wf_kicker: "Cómo funciona",
    wf_title: "Del archivo abierto a la exportación redactada",
    wf_step1_title: "Abrir y analizar",
    wf_step1_desc: "Carga un PDF y ejecuta la detección para los formatos de tu región.",
    wf_step2_title: "Revisar señalizaciones",
    wf_step2_desc: "Consulta cada elemento marcado con su categoría de riesgo.",
    wf_step3_title: "Ajustar manualmente",
    wf_step3_desc: "Añade, elimina o afina antes de finalizar.",
    wf_step4_title: "Exportar",
    wf_step4_desc: "Contenido y metadatos eliminados permanentemente.",
    how_li1:
      "Detección automática — Nombres, números de ID, teléfonos, direcciones y cuentas financieras en 28 formatos de países, sin empezar desde cero.",
    how_li2:
      "Panel de revisión manual — Revisa cada elemento marcado antes de exportar. Añade, elimina o ajusta — la automatización es el punto de partida, no la palabra final.",
    how_li3:
      "Eliminación real, no enmascaramiento — El contenido se retira del archivo, no solo se cubre. También se eliminan metadatos sensibles.",
    how_li4: "Procesamiento por lotes — Aplica las mismas reglas a varios archivos a la vez.",
    scenarios_title: "Diseñado para cómo trabajan los profesionales independientes",
    scenario_attorney_label: "Para abogados",
    scenario_attorney_body:
      "Redacta SSN, datos financieros y otros PII antes de e-filing o compartir discovery, sin pasar archivos de clientes por nube de terceros.",
    scenario_accountant_label: "Para contadores",
    scenario_accountant_body:
      "Redacta números de cuenta, SSN y datos financieros del cliente antes de compartir papeles de trabajo de auditoría, declaraciones fiscales o informes de fin de año — sin pasar datos del cliente por nube de terceros.",
    scenario_hr_label: "Para equipos de RR. HH.",
    scenario_hr_body:
      "Redacta cifras salariales, SSN y datos personales antes de compartir cartas de oferta, registros de terminación o expedientes de personal con auditores, asesores legales o en respuesta a solicitudes de datos.",
    scenario_attorney:
      "Para abogados — Redacta SSN, datos financieros y otros PII antes de e-filing o compartir discovery, sin pasar archivos de clientes por nube de terceros.",
    scenario_accountant:
      "Para contadores — Redacta números de cuenta, SSN y datos financieros del cliente antes de compartir papeles de trabajo de auditoría, declaraciones fiscales o informes de fin de año, sin pasar datos del cliente por nube de terceros.",
    included_title: "Qué incluye hoy",
    included_li1: "Redacción física",
    included_li2: "Interfaz en 12 idiomas",
    included_li3: "Reglas para 28 países",
    included_li4: "Procesamiento por lotes",
    pricing_title: "Precios",
    pricing_body:
      "Prueba todas las funciones gratis durante 10 días. Después, un pago único de $34 desbloquea la versión completa — sin suscripción ni tarifas recurrentes.",
    pillar1_h: "Procesamiento 100% offline",
    pillar2_h: "Exportación con redacción física",
    pillar3_h: "IA en el dispositivo + reglas regionales",
    section_everything: "Todo lo que necesitas",
    section_everything_lead: "Detecta, revisa, redacta y exporta — todo offline.",
    everything_li1: "Trazabilidad de auditoría en paralelo con elementos agrupados y señales de riesgo claras",
    everything_li2: "Exportación con redacción física: el contenido sensible se elimina del PDF, no solo se cubre",
    everything_li3: "IA en el dispositivo y más de 145 reglas regionales integradas para datos estructurados",
    everything_li4: "Lotes: aplica las marcas confirmadas del PDF base a archivos similares",
    everything_li5: "100% privado — sin nube, sin subidas",
    everything_li6: "Interfaz en 12 idiomas · renderizado nativo rápido · exportación con enfoque en metadatos",
    regional_title: "Reglas regionales de detección integradas",
    workflow_title: "Revisa más rápido. Exporta con seguridad.",
    wf1_h: "Revisión lado a lado",
    wf2_h: "Procesamiento por lotes de PDF similares",
    wf3_h: "Panel de auditoría enfocado",
    early_title: "Por qué es gratis durante el acceso anticipado",
    early_body:
      "Durante la fase early adopter, el producto es gratuito para validar flujos reales, mejorar la detección y aumentar la estabilidad.",
    early_c1: "La arquitectura local-first seguirá siendo un principio central del producto.",
    early_c2: "El flujo principal de redacción no depende de subidas a la nube.",
    early_c3: "Los usuarios tempranos ayudan a definir roadmap y baseline de calidad.",
    early_note:
      "No prometemos acceso gratuito permanente a todas las funciones futuras, seguridad absoluta ni certificaciones no obtenidas.",
    rm_v10: "v1.0 (Actual)",
    rm_v10_li1: "Flujo principal de redacción física",
    rm_v10_li2: "Interfaz en 12 idiomas",
    rm_v10_li3: "Cobertura en más de 20 regiones",
    rm_v10_li4: "Procesamiento por lotes",
    rm_v12: "v1.2 (Planificado)",
    rm_v12_li1: "OCR offline para PDF escaneados",
    rm_v12_li2: "Editor de reglas personalizadas",
    rm_v15: "v1.5 (Planificado)",
    rm_v15_li1: "Exportación local de informe de auditoría",
    rm_v15_li2: "Más herramientas de verificación y revisión",
    rm_v20: "v2.0 (Visión)",
    rm_v20_li1: "Soporte multiplataforma",
    rm_v20_li2: "Flujos avanzados de enmascarado semántico",
    foot_sup: "Soporte y comentarios",
    foot_email: "Correo de soporte",
    foot_quick: "Guía rápida",
    foot_privacy: "Política de privacidad",
    quickstart_title: "Guía rápida",
    quickstart_body:
      "Instala desde Microsoft Store o tu paquete distribuido. Abre un PDF, ejecuta la detección, revisa en el panel de auditoría, confirma y exporta.",
    privacy_title: "Política de privacidad",
    privacy_body:
      "El flujo principal de redacción procesa los PDF localmente y no envía el contenido de tus documentos a los servidores de PlainBytes.",
  };

  STR.nl = {
    ...STR.en,
    nav_home: "Start",
    nav_guide: "Gebruikershandleiding",
    nav_features: "Functies",
    nav_regional: "Regionale regels",
    nav_roadmap: "Roadmap",
    nav_support: "Ondersteuning",
    nav_download: "Downloaden via Microsoft Store",
    hero_kicker: "PlainBytes Redactor",
    hero_tagline: "PDF's redigeren zonder klantgegevens ergens naartoe te sturen.",
    hero_lead:
      "PlainBytes Redactor draait volledig op je computer — geen cloud-upload, geen AI-dienst die je bestanden ziet. Automatische detectie voor identificatieformaten uit 28 landen, plus handmatige controle vóór export.",
    hero_cta_secondary: "Demo bekijken",
    hero_badge_3: "28 landen",
    hero_badge_4: "Handmatige controle",
    hero_note: "10 dagen gratis proberen · Eenmalige aankoop · Geen abonnement",
    trust_title: "Waarom verwerking lokaal blijft",
    trust_body_p1:
      "De meeste redactietools — vooral AI-gestuurde — uploaden je documenten naar een server voordat ze gevoelige informatie kunnen vinden en verwijderen. Voor wie gebonden is aan vertrouwelijkheid, privilege of auditonafhankelijkheid, hoort dat geen risico te zijn alleen om een bestand te redigeren.",
    trust_body_p2:
      "PlainBytes Redactor voert alle detectie en verwerking uit op je apparaat. Je bestanden verlaten je computer nooit — geen account, geen sync, geen server.",
    section_how_title: "Zo werkt het",
    wf_kicker: "Zo werkt het",
    wf_title: "Van geopend bestand tot geredigeerde export",
    wf_step1_title: "Openen en scannen",
    wf_step1_desc: "Laad een PDF en voer detectie uit voor de formaten in uw regio.",
    wf_step2_title: "Markeringen beoordelen",
    wf_step2_desc: "Bekijk elk gemarkeerd item met de bijbehorende risicocategorie.",
    wf_step3_title: "Handmatig aanpassen",
    wf_step3_desc: "Voeg toe, verwijder of verfijn vóór afronding.",
    wf_step4_title: "Exporteren",
    wf_step4_desc: "Inhoud en metadata permanent verwijderd.",
    how_li1:
      "Automatische detectie — Namen, ID-nummers, telefoons, adressen en financiële rekeningen in 28 landformaten, zonder vanaf nul te beginnen.",
    how_li2:
      "Handmatig controlepaneel — Controleer elk gemarkeerd item vóór export. Voeg toe, verwijder of pas aan — automatisering is het startpunt, niet het laatste woord.",
    how_li3:
      "Echte verwijdering, geen maskering — Inhoud wordt uit het bestand gehaald, niet alleen bedekt. Gevoelige metadata wordt ook verwijderd.",
    how_li4: "Batchverwerking — Pas dezelfde regels tegelijk toe op meerdere bestanden.",
    scenarios_title: "Gebouwd voor hoe solo-praktijken echt werken",
    scenario_attorney_label: "Voor advocaten",
    scenario_attorney_body:
      "Redigeer SSN, financiële gegevens en andere PII vóór e-filing of discovery-deling, zonder klantbestanden via cloud van derden te leiden.",
    scenario_accountant_label: "Voor accountants",
    scenario_accountant_body:
      "Redigeer rekeningnummers, SSN en financiële klantgegevens vóór het delen van audit working papers, belastingaangiften of jaarverslagen — zonder klantgegevens via cloud van derden te leiden.",
    scenario_hr_label: "Voor HR-teams",
    scenario_hr_body:
      "Redigeer salarisbedragen, SSN en persoonlijke gegevens vóór het delen van aanbiedingsbrieven, beëindigingsdossiers of personeelsbestanden met auditors, juridisch adviseurs of bij datverzoeken.",
    scenario_attorney:
      "Voor advocaten — Redigeer SSN, financiële gegevens en andere PII vóór e-filing of discovery-deling, zonder klantbestanden via cloud van derden te leiden.",
    scenario_accountant:
      "Voor accountants — Redigeer rekeningnummers, SSN en financiële klantgegevens vóór het delen van audit working papers, belastingaangiften of jaarverslagen, zonder klantgegevens via cloud van derden te leiden.",
    included_title: "Wat vandaag is inbegrepen",
    included_li1: "Fysieke redactie",
    included_li2: "Interface in 12 talen",
    included_li3: "Regels voor 28 landen",
    included_li4: "Batchverwerking",
    pricing_title: "Prijzen",
    pricing_body:
      "Probeer 10 dagen alle functies gratis. Daarna een eenmalige betaling van $34 voor de volledige versie — geen abonnement, geen terugkerende kosten.",
    pillar1_h: "100% offline verwerking",
    pillar2_h: "Export met fysieke redactie",
    pillar3_h: "AI op het apparaat + regionale regels",
    section_everything: "Alles wat je nodig hebt",
    section_everything_lead: "Detecteren, controleren, redigeren en exporteren — volledig offline.",
    everything_li1: "Auditspoor naast elkaar met gegroepeerde items en duidelijke risicosignalen",
    everything_li2: "Fysieke redactie-export — gevoelige inhoud wordt uit de PDF verwijderd, niet alleen afgedekt",
    everything_li3: "AI op het apparaat en 145+ ingebouwde regionale regels voor gestructureerde gegevens",
    everything_li4: "Batch: bevestigde markeringen uit een basis-PDF toepassen op vergelijkbare bestanden",
    everything_li5: "100% privé — geen cloud, geen uploads",
    everything_li6: "UI in 12 talen · snelle native rendering · metadata-bewuste export",
    regional_title: "Ingebouwde regionale detectieregels",
    workflow_title: "Sneller beoordelen. Veiliger exporteren.",
    wf1_h: "Review naast elkaar",
    wf2_h: "Batchverwerking voor vergelijkbare PDF's",
    wf3_h: "Gericht auditpaneel",
    early_title: "Waarom gratis tijdens early access",
    early_body:
      "Tijdens de early-adopterfase is het product gratis om echte workflows te valideren, detectiekwaliteit te verbeteren en stabiliteit te verhogen.",
    early_c1: "De local-first architectuur blijft een kernprincipe van het product.",
    early_c2: "De kernworkflow is niet afhankelijk van cloud-uploads.",
    early_c3: "Vroege gebruikers helpen roadmap en kwaliteitsbasis vorm te geven.",
    early_note:
      "We beloven geen permanente gratis toegang tot alle toekomstige functies, absolute veiligheid of niet-verkregen certificeringen.",
    rm_v10: "v1.0 (Huidig)",
    rm_v10_li1: "Kernworkflow voor fysieke redactie",
    rm_v10_li2: "Interface in 12 talen",
    rm_v10_li3: "Dekking van 20+ regio's",
    rm_v10_li4: "Batchverwerking",
    rm_v12: "v1.2 (Gepland)",
    rm_v12_li1: "Offline OCR voor gescande PDF's",
    rm_v12_li2: "Editor voor aangepaste regels",
    rm_v15: "v1.5 (Gepland)",
    rm_v15_li1: "Lokale export van auditrapport",
    rm_v15_li2: "Meer verificatie- en reviewtools",
    rm_v20: "v2.0 (Visie)",
    rm_v20_li1: "Cross-platform ondersteuning",
    rm_v20_li2: "Geavanceerde semantische masking-workflows",
    foot_sup: "Ondersteuning en feedback",
    foot_email: "Support e-mail",
    foot_quick: "Snelstart",
    foot_privacy: "Privacybeleid",
    quickstart_title: "Snelstart",
    quickstart_body:
      "Installeer via Microsoft Store of je distributiepakket. Open een PDF, start detectie, controleer in het auditpaneel, bevestig en exporteer.",
    privacy_title: "Privacybeleid",
    privacy_body:
      "De kernworkflow verwerkt PDF's lokaal en stuurt geen documentinhoud naar de servers van PlainBytes.",
  };

  STR.ru = {
    ...STR.en,
    nav_home: "Главная",
    nav_guide: "Руководство пользователя",
    nav_features: "Функции",
    nav_regional: "Региональные правила",
    nav_roadmap: "Дорожная карта",
    nav_support: "Поддержка",
    nav_download: "Получить в Microsoft Store",
    hero_kicker: "PlainBytes Redactor",
    hero_tagline: "Редактируйте PDF, не отправляя данные клиентов никуда.",
    hero_lead:
      "PlainBytes Redactor работает полностью на вашем компьютере — без загрузки в облако, без AI-сервисов, видящих ваши файлы. Автообнаружение форматов идентификаторов 28 стран и ручная проверка перед экспортом.",
    hero_cta_secondary: "Смотреть демо",
    hero_badge_3: "28 стран",
    hero_badge_4: "Ручная проверка",
    hero_note: "10 дней бесплатно · Разовая покупка · Без подписки",
    trust_title: "Почему обработка остаётся локальной",
    trust_body_p1:
      "Большинство инструментов редактирования — особенно на базе ИИ — загружают документы на сервер, прежде чем найти и удалить конфиденциальную информацию. Для тех, кто связан обязательствами конфиденциальности, привилегией или независимостью аудита, такой риск не нужен только ради редактирования файла.",
    trust_body_p2:
      "PlainBytes Redactor выполняет всё обнаружение и обработку на вашем устройстве. Файлы не покидают компьютер — без аккаунта, синхронизации и сервера.",
    section_how_title: "Как это работает",
    wf_kicker: "Как это работает",
    wf_title: "От открытия файла до редактированного экспорта",
    wf_step1_title: "Открыть и сканировать",
    wf_step1_desc: "Загрузите PDF и запустите обнаружение для форматов вашего региона.",
    wf_step2_title: "Проверить метки",
    wf_step2_desc: "Просмотрите каждый помеченный элемент с категорией риска.",
    wf_step3_title: "Настроить вручную",
    wf_step3_desc: "Добавляйте, удаляйте или уточняйте перед завершением.",
    wf_step4_title: "Экспорт",
    wf_step4_desc: "Содержимое и метаданные удалены безвозвратно.",
    how_li1:
      "Автообнаружение — Имена, номера ID, телефоны, адреса и финансовые счета в форматах 28 стран, без начала с нуля.",
    how_li2:
      "Панель ручной проверки — Проверьте каждый помеченный элемент перед экспортом. Добавляйте, удаляйте или корректируйте — автоматизация это старт, не финальное решение.",
    how_li3:
      "Настоящее удаление, не маскировка — Содержимое удаляется из файла, а не просто закрывается. Метаданные с чувствительными данными тоже очищаются.",
    how_li4: "Пакетная обработка — Применяйте одни правила к нескольким файлам сразу.",
    scenarios_title: "Для реальной работы частных практиков",
    scenario_attorney_label: "Для адвокатов",
    scenario_attorney_body:
      "Редактируйте SSN, финансовые данные и другие PII перед e-filing или discovery, не направляя файлы клиентов через облако третьих лиц.",
    scenario_accountant_label: "Для бухгалтеров",
    scenario_accountant_body:
      "Редактируйте номера счетов, SSN и финансовые данные клиентов перед передачей рабочих бумаг аудита, налоговых деклараций или годовых отчётов — не направляя данные клиентов через облако третьих лиц.",
    scenario_hr_label: "Для HR-команд",
    scenario_hr_body:
      "Редактируйте суммы зарплат, SSN и личные данные перед передачей офферов, записей об увольнении или кадровых файлов аудиторам, юристам или в ответ на запросы данных.",
    scenario_attorney:
      "Для адвокатов — Редактируйте SSN, финансовые данные и другие PII перед e-filing или discovery, не направляя файлы клиентов через облако третьих лиц.",
    scenario_accountant:
      "Для бухгалтеров — Редактируйте номера счетов, SSN и финансовые данные клиентов перед передачей рабочих бумаг аудита, налоговых деклараций или годовых отчётов, не направляя данные клиентов через облако третьих лиц.",
    included_title: "Что включено сегодня",
    included_li1: "Физическое редактирование",
    included_li2: "Интерфейс на 12 языках",
    included_li3: "Правила для 28 стран",
    included_li4: "Пакетная обработка",
    pricing_title: "Цены",
    pricing_body:
      "10 дней бесплатно со всеми функциями. Затем единоразовый платёж $34 за полную версию — без подписки и регулярных платежей.",
    pillar1_h: "100% офлайн-обработка",
    pillar2_h: "Экспорт с физическим редактированием",
    pillar3_h: "ИИ на устройстве + региональные правила",
    section_everything: "Все, что нужно",
    section_everything_lead: "Обнаружение, проверка, редактирование и экспорт — полностью офлайн.",
    everything_li1: "Панель аудита рядом: группировка элементов и понятные индикаторы риска",
    everything_li2: "Экспорт с физическим редактированием — чувствительное содержимое удаляется из PDF, а не только закрывается",
    everything_li3: "ИИ на устройстве и более 145 встроенных региональных правил для структурированных данных",
    everything_li4: "Пакетная обработка: применяйте подтвержденные метки из базового PDF к похожим файлам",
    everything_li5: "100% приватно — без облака и загрузок",
    everything_li6: "Интерфейс на 12 языках · быстрое нативное рендеринг · экспорт с учетом метаданных",
    regional_title: "Встроенные региональные правила обнаружения",
    workflow_title: "Проверяйте быстрее. Экспортируйте безопаснее.",
    wf1_h: "Проверка бок о бок",
    wf2_h: "Пакетная обработка похожих PDF",
    wf3_h: "Фокусная панель аудита",
    early_title: "Почему бесплатно в раннем доступе",
    early_body:
      "В период early adopter продукт бесплатен для проверки реальных сценариев, улучшения качества обнаружения и повышения стабильности.",
    early_c1: "Архитектура local-first остается базовым принципом продукта.",
    early_c2: "Ключевой процесс редактирования не зависит от облачных загрузок.",
    early_c3: "Ранние пользователи помогают формировать дорожную карту и стандарты качества.",
    early_note:
      "Мы не обещаем постоянную бесплатность всех будущих функций, абсолютную безопасность или отсутствующие сертификации.",
    rm_v10: "v1.0 (Текущая)",
    rm_v10_li1: "Базовый процесс физического редактирования",
    rm_v10_li2: "Интерфейс на 12 языках",
    rm_v10_li3: "Покрытие более 20 регионов",
    rm_v10_li4: "Пакетная обработка",
    rm_v12: "v1.2 (План)",
    rm_v12_li1: "Офлайн OCR для сканированных PDF",
    rm_v12_li2: "Редактор пользовательских правил",
    rm_v15: "v1.5 (План)",
    rm_v15_li1: "Локальный экспорт аудиторского отчета",
    rm_v15_li2: "Больше инструментов проверки и ревью",
    rm_v20: "v2.0 (Видение)",
    rm_v20_li1: "Кроссплатформенная поддержка",
    rm_v20_li2: "Продвинутые сценарии семантического маскирования",
    foot_sup: "Поддержка и обратная связь",
    foot_email: "Почта поддержки",
    foot_quick: "Быстрый старт",
    foot_privacy: "Политика конфиденциальности",
    quickstart_title: "Быстрый старт",
    quickstart_body:
      "Установите из Microsoft Store или из пакета дистрибуции. Откройте PDF, запустите обнаружение, проверьте результаты в панели аудита, подтвердите и экспортируйте.",
    privacy_title: "Политика конфиденциальности",
    privacy_body:
      "Основной процесс редактирования обрабатывает PDF локально и не отправляет содержимое документов на серверы PlainBytes.",
  };

const FALLBACK_LANG = {
  "zh-Hant": "zh",
};

function t(lang, key) {
  const pack = STR[lang] || STR.en;
  if (pack[key] != null) return pack[key];
  const fallback = FALLBACK_LANG[lang];
  if (fallback && STR[fallback] && STR[fallback][key] != null) return STR[fallback][key];
  return STR.en[key] != null ? STR.en[key] : key;
}

module.exports = { STR, FALLBACK_LANG, t };
